//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPROCUREMENT.GAPPROVEEDOR.Data.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StoredProcedures {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StoredProcedures() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EPROCUREMENT.GAPPROVEEDOR.Data.App_GlobalResources.StoredProcedures", typeof(StoredProcedures).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[usp_EPROCUREMENT_Aeropuerto_GETL].
        /// </summary>
        internal static string usp_EPROCUREMENT_Aeropuerto_GETL {
            get {
                return ResourceManager.GetString("usp_EPROCUREMENT_Aeropuerto_GETL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[usp_EPROCUREMENT_Aeropuerto_GETLByIdProveedorCuenta].
        /// </summary>
        internal static string usp_EPROCUREMENT_Aeropuerto_GETLByIdProveedorCuenta {
            get {
                return ResourceManager.GetString("usp_EPROCUREMENT_Aeropuerto_GETLByIdProveedorCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[usp_EPROCUREMENT_Banco_GETL].
        /// </summary>
        internal static string usp_EPROCUREMENT_Banco_GETL {
            get {
                return ResourceManager.GetString("usp_EPROCUREMENT_Banco_GETL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[usp_EPROCUREMENT_CatalogoDocumento_GETL].
        /// </summary>
        internal static string usp_EPROCUREMENT_CatalogoDocumento_GETL {
            get {
                return ResourceManager.GetString("usp_EPROCUREMENT_CatalogoDocumento_GETL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[usp_EPROCUREMENT_CatalogoGiro_GETL].
        /// </summary>
        internal static string usp_EPROCUREMENT_CatalogoGiro_GETL {
            get {
                return ResourceManager.GetString("usp_EPROCUREMENT_CatalogoGiro_GETL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[usp_EPROCUREMENT_CuentaEmpresa_INS].
        /// </summary>
        internal static string usp_EPROCUREMENT_CuentaEmpresa_INS {
            get {
                return ResourceManager.GetString("usp_EPROCUREMENT_CuentaEmpresa_INS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[usp_EPROCUREMENT_Estado_GETL].
        /// </summary>
        internal static string usp_EPROCUREMENT_Estado_GETL {
            get {
                return ResourceManager.GetString("usp_EPROCUREMENT_Estado_GETL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[usp_EPROCUREMENT_EstatusProveedor_INS].
        /// </summary>
        internal static string usp_EPROCUREMENT_EstatusProveedor_INS {
            get {
                return ResourceManager.GetString("usp_EPROCUREMENT_EstatusProveedor_INS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[usp_EPROCUREMENT_FormatoArchivo_GETL].
        /// </summary>
        internal static string usp_EPROCUREMENT_FormatoArchivo_GETL {
            get {
                return ResourceManager.GetString("usp_EPROCUREMENT_FormatoArchivo_GETL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[usp_EPROCUREMENT_Idioma_GETL].
        /// </summary>
        internal static string usp_EPROCUREMENT_Idioma_GETL {
            get {
                return ResourceManager.GetString("usp_EPROCUREMENT_Idioma_GETL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[usp_EPROCUREMENT_Municipio_GETL].
        /// </summary>
        internal static string usp_EPROCUREMENT_Municipio_GETL {
            get {
                return ResourceManager.GetString("usp_EPROCUREMENT_Municipio_GETL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[usp_EPROCUREMENT_Nacionalidad_GETL].
        /// </summary>
        internal static string usp_EPROCUREMENT_Nacionalidad_GETL {
            get {
                return ResourceManager.GetString("usp_EPROCUREMENT_Nacionalidad_GETL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[usp_EPROCUREMENT_Pais_GETL].
        /// </summary>
        internal static string usp_EPROCUREMENT_Pais_GETL {
            get {
                return ResourceManager.GetString("usp_EPROCUREMENT_Pais_GETL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[usp_EPROCUREMENT_Proveedor_GETIById].
        /// </summary>
        internal static string usp_EPROCUREMENT_Proveedor_GETIById {
            get {
                return ResourceManager.GetString("usp_EPROCUREMENT_Proveedor_GETIById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[usp_EPROCUREMENT_Proveedor_GETLByFilter].
        /// </summary>
        internal static string usp_EPROCUREMENT_Proveedor_GETLByFilter {
            get {
                return ResourceManager.GetString("usp_EPROCUREMENT_Proveedor_GETLByFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[usp_EPROCUREMENT_Proveedor_INS].
        /// </summary>
        internal static string usp_EPROCUREMENT_Proveedor_INS {
            get {
                return ResourceManager.GetString("usp_EPROCUREMENT_Proveedor_INS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[usp_EPROCUREMENT_ProveedorContacto_GETIByIdProveedor].
        /// </summary>
        internal static string usp_EPROCUREMENT_ProveedorContacto_GETIByIdProveedor {
            get {
                return ResourceManager.GetString("usp_EPROCUREMENT_ProveedorContacto_GETIByIdProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[usp_EPROCUREMENT_ProveedorContacto_INS].
        /// </summary>
        internal static string usp_EPROCUREMENT_ProveedorContacto_INS {
            get {
                return ResourceManager.GetString("usp_EPROCUREMENT_ProveedorContacto_INS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[usp_EPROCUREMENT_ProveedorCuenta_GETLByIdProveedor].
        /// </summary>
        internal static string usp_EPROCUREMENT_ProveedorCuenta_GETLByIdProveedor {
            get {
                return ResourceManager.GetString("usp_EPROCUREMENT_ProveedorCuenta_GETLByIdProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[usp_EPROCUREMENT_ProveedorCuenta_INS].
        /// </summary>
        internal static string usp_EPROCUREMENT_ProveedorCuenta_INS {
            get {
                return ResourceManager.GetString("usp_EPROCUREMENT_ProveedorCuenta_INS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[usp_EPROCUREMENT_ProveedorDireccion_GETIByIdProveedor].
        /// </summary>
        internal static string usp_EPROCUREMENT_ProveedorDireccion_GETIByIdProveedor {
            get {
                return ResourceManager.GetString("usp_EPROCUREMENT_ProveedorDireccion_GETIByIdProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[usp_EPROCUREMENT_ProveedorDireccion_INS].
        /// </summary>
        internal static string usp_EPROCUREMENT_ProveedorDireccion_INS {
            get {
                return ResourceManager.GetString("usp_EPROCUREMENT_ProveedorDireccion_INS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[usp_EPROCUREMENT_ProveedorDocumento_GETLByIdProveedor].
        /// </summary>
        internal static string usp_EPROCUREMENT_ProveedorDocumento_GETLByIdProveedor {
            get {
                return ResourceManager.GetString("usp_EPROCUREMENT_ProveedorDocumento_GETLByIdProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[usp_EPROCUREMENT_ProveedorDocumento_INS].
        /// </summary>
        internal static string usp_EPROCUREMENT_ProveedorDocumento_INS {
            get {
                return ResourceManager.GetString("usp_EPROCUREMENT_ProveedorDocumento_INS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[usp_EPROCUREMENT_ProveedorEmpresa_GETLByIdProveedor].
        /// </summary>
        internal static string usp_EPROCUREMENT_ProveedorEmpresa_GETLByIdProveedor {
            get {
                return ResourceManager.GetString("usp_EPROCUREMENT_ProveedorEmpresa_GETLByIdProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[usp_EPROCUREMENT_ProveedorEmpresa_INS].
        /// </summary>
        internal static string usp_EPROCUREMENT_ProveedorEmpresa_INS {
            get {
                return ResourceManager.GetString("usp_EPROCUREMENT_ProveedorEmpresa_INS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[usp_EPROCUREMENT_ProveedorGiro_GETLByIdProveedor].
        /// </summary>
        internal static string usp_EPROCUREMENT_ProveedorGiro_GETLByIdProveedor {
            get {
                return ResourceManager.GetString("usp_EPROCUREMENT_ProveedorGiro_GETLByIdProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[usp_EPROCUREMENT_ProveedorGiro_INS].
        /// </summary>
        internal static string usp_EPROCUREMENT_ProveedorGiro_INS {
            get {
                return ResourceManager.GetString("usp_EPROCUREMENT_ProveedorGiro_INS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[usp_EPROCUREMENT_ProveedorUsuario_GETIById].
        /// </summary>
        internal static string usp_EPROCUREMENT_ProveedorUsuario_GETIById {
            get {
                return ResourceManager.GetString("usp_EPROCUREMENT_ProveedorUsuario_GETIById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[usp_EPROCUREMENT_ProveedorUsuario_GETIByNombreUsuario].
        /// </summary>
        internal static string usp_EPROCUREMENT_ProveedorUsuario_GETIByNombreUsuario {
            get {
                return ResourceManager.GetString("usp_EPROCUREMENT_ProveedorUsuario_GETIByNombreUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[usp_EPROCUREMENT_RecoveryPassword_UPD].
        /// </summary>
        internal static string usp_EPROCUREMENT_RecoveryPassword_UPD {
            get {
                return ResourceManager.GetString("usp_EPROCUREMENT_RecoveryPassword_UPD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[usp_EPROCUREMENT_TipoCuenta_GETL].
        /// </summary>
        internal static string usp_EPROCUREMENT_TipoCuenta_GETL {
            get {
                return ResourceManager.GetString("usp_EPROCUREMENT_TipoCuenta_GETL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[usp_EPROCUREMENT_TipoProveedor_GETL].
        /// </summary>
        internal static string usp_EPROCUREMENT_TipoProveedor_GETL {
            get {
                return ResourceManager.GetString("usp_EPROCUREMENT_TipoProveedor_GETL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[usp_EPROCUREMENT_Usuario_GETIByLogin].
        /// </summary>
        internal static string usp_EPROCUREMENT_Usuario_GETIByLogin {
            get {
                return ResourceManager.GetString("usp_EPROCUREMENT_Usuario_GETIByLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[usp_EPROCUREMENT_Usuario_GEToken].
        /// </summary>
        internal static string usp_EPROCUREMENT_Usuario_GEToken {
            get {
                return ResourceManager.GetString("usp_EPROCUREMENT_Usuario_GEToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[usp_EPROCUREMENT_UsuarioInterno_INS].
        /// </summary>
        internal static string usp_EPROCUREMENT_UsuarioInterno_INS {
            get {
                return ResourceManager.GetString("usp_EPROCUREMENT_UsuarioInterno_INS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[usp_EPROCUREMENT_UsuarioProveedor_INS].
        /// </summary>
        internal static string usp_EPROCUREMENT_UsuarioProveedor_IN {
            get {
                return ResourceManager.GetString("usp_EPROCUREMENT_UsuarioProveedor_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[usp_EPROCUREMENT_ZonaHoraria_GETL].
        /// </summary>
        internal static string usp_EPROCUREMENT_ZonaHoraria_GETL {
            get {
                return ResourceManager.GetString("usp_EPROCUREMENT_ZonaHoraria_GETL", resourceCulture);
            }
        }
    }
}
