//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EprocurementWeb.GlobalResources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RHome {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RHome() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EprocurementWeb.GlobalResources.RHome", typeof(RHome).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nosotros.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalles sobre tu información personal o la información de tu compañía.
        /// </summary>
        public static string AboutDetails {
            get {
                return ResourceManager.GetString("AboutDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu información personal o la información de tu compañía.
        /// </summary>
        public static string AboutMessage {
            get {
                return ResourceManager.GetString("AboutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuenta*.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Calle y número*.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Marque los Aeropuertos que puede atender*.
        /// </summary>
        public static string AeropuertosAtender {
            get {
                return ResourceManager.GetString("AeropuertosAtender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Es necesario aceptar el aviso de privacidad.
        /// </summary>
        public static string AvisoPrivacidadAceptar {
            get {
                return ResourceManager.GetString("AvisoPrivacidadAceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de proveedor AX.
        /// </summary>
        public static string AXProviderNum {
            get {
                return ResourceManager.GetString("AXProviderNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Banco.
        /// </summary>
        public static string Bank {
            get {
                return ResourceManager.GetString("Bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Razón Social*.
        /// </summary>
        public static string BName {
            get {
                return ResourceManager.GetString("BName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categoria.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de célular.
        /// </summary>
        public static string CellPhone {
            get {
                return ResourceManager.GetString("CellPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Municipio.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CLABE*.
        /// </summary>
        public static string CLABE {
            get {
                return ResourceManager.GetString("CLABE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de contacto*.
        /// </summary>
        public static string CName {
            get {
                return ResourceManager.GetString("CName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Extranjera.
        /// </summary>
        public static string CompanyTypeInternational {
            get {
                return ResourceManager.GetString("CompanyTypeInternational", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mexicana.
        /// </summary>
        public static string CompanyTypeMexican {
            get {
                return ResourceManager.GetString("CompanyTypeMexican", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Empresa*.
        /// </summary>
        public static string CompanyTypeTitle {
            get {
                return ResourceManager.GetString("CompanyTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contacto.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo electrónico*.
        /// </summary>
        public static string ContactEmail {
            get {
                return ResourceManager.GetString("ContactEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu información de contacto.
        /// </summary>
        public static string ContactMessage {
            get {
                return ResourceManager.GetString("ContactMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El mensaje no ha podido ser enviado con éxito. Prueba de nuevo..
        /// </summary>
        public static string ContactMessageSendNok {
            get {
                return ResourceManager.GetString("ContactMessageSendNok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El mensaje se ha enviado con éxito. Muchas gracias..
        /// </summary>
        public static string ContactMessageSendOk {
            get {
                return ResourceManager.GetString("ContactMessageSendOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de Contacto*.
        /// </summary>
        public static string ContactName {
            get {
                return ResourceManager.GetString("ContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ASP.NET MVC le ofrece una potente manera basada en patrones para crear sitios web dinámicos que permite una separación clara de las preocupaciones y le da un control total sobre el marcado para un desarrollo ágil y agradable..
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a País.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de teléfono.
        /// </summary>
        public static string CPhone {
            get {
                return ResourceManager.GetString("CPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione una opción.
        /// </summary>
        public static string DefaultSelect {
            get {
                return ResourceManager.GetString("DefaultSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email*.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fax.
        /// </summary>
        public static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Llene los carácteres.
        /// </summary>
        public static string FillC {
            get {
                return ResourceManager.GetString("FillC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma*.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Marketing.
        /// </summary>
        public static string Marketing {
            get {
                return ResourceManager.GetString("Marketing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo {0} es obligatorio.
        /// </summary>
        public static string Mensaje_Error_Required {
            get {
                return ResourceManager.GetString("Mensaje_Error_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo {0} debe tener mínimo {2} y máximo {1} caracteres.
        /// </summary>
        public static string Mensaje_Error_StringLength {
            get {
                return ResourceManager.GetString("Mensaje_Error_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mensaje.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe ingresar un Email valido, ejemplo (usuario@dominio.com).
        /// </summary>
        public static string Message_Error_Email {
            get {
                return ResourceManager.GetString("Message_Error_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar al menos un aeropuerto.
        /// </summary>
        public static string Message_Error_Required_Airport {
            get {
                return ResourceManager.GetString("Message_Error_Required_Airport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El documento es requerido.
        /// </summary>
        public static string Message_Error_Required_Document {
            get {
                return ResourceManager.GetString("Message_Error_Required_Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo es requerido.
        /// </summary>
        public static string Message_Error_Required_Generic {
            get {
                return ResourceManager.GetString("Message_Error_Required_Generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nacionalidad*.
        /// </summary>
        public static string Nacionality {
            get {
                return ResourceManager.GetString("Nacionality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reg. Nombre de la empresa*.
        /// </summary>
        public static string NameOfCompany {
            get {
                return ResourceManager.GetString("NameOfCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NIF.
        /// </summary>
        public static string NIF {
            get {
                return ResourceManager.GetString("NIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargo.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contacto Principal.
        /// </summary>
        public static string PrincipalContacto {
            get {
                return ResourceManager.GetString("PrincipalContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Favor de seleccionar el (los) giro (s) específicos que su empresa esta calificada*.
        /// </summary>
        public static string ProveedorGiros {
            get {
                return ResourceManager.GetString("ProveedorGiros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PORTAL DE PROVEEDORES.
        /// </summary>
        public static string ProvP {
            get {
                return ResourceManager.GetString("ProvP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de proveedor.
        /// </summary>
        public static string ProvType {
            get {
                return ResourceManager.GetString("ProvType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RFC*.
        /// </summary>
        public static string RFC {
            get {
                return ResourceManager.GetString("RFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ASP.NET es un marco web gratuito para la creación de grandes sitios web multilingües MVC y aplicaciones Web mediante HTML, CSS y JavaScript..
        /// </summary>
        public static string Subtitle {
            get {
                return ResourceManager.GetString("Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Colonia.
        /// </summary>
        public static string Suburb {
            get {
                return ResourceManager.GetString("Suburb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Soporte.
        /// </summary>
        public static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TIN.
        /// </summary>
        public static string TIN {
            get {
                return ResourceManager.GetString("TIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EProcurement.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alta de proveedores.
        /// </summary>
        public static string TitlePP {
            get {
                return ResourceManager.GetString("TitlePP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Es necesario aceptar los términos y condiciones..
        /// </summary>
        public static string TituloTerminos {
            get {
                return ResourceManager.GetString("TituloTerminos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Zona honoraria*.
        /// </summary>
        public static string TZone {
            get {
                return ResourceManager.GetString("TZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Página Web.
        /// </summary>
        public static string WPage {
            get {
                return ResourceManager.GetString("WPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código Postal*.
        /// </summary>
        public static string ZipCode {
            get {
                return ResourceManager.GetString("ZipCode", resourceCulture);
            }
        }
    }
}
